import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
const PromptRegular = Prompt({
  subsets:["latin"],
  variable:"--font-prompt-sans-serif",
  weight: "300",
  display: "swap"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${PromptRegular.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
